name: mlip_challenge_2
channels:
  - defaults
  - pytorch
  - conda-forge
  - h2oai
dependencies:
  - python=3.7.12
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision
  - matplotlib
  - ipykernel
  - ipywidgets
  - numpy
  - scikit-learn
  - albumentations
  - pillow
  - scipy
  - pip
  - pandas
  - pytorch-lightning
  - seaborn
  - fairscale
  - py-xgboost
  - h2o
  - pip:
    - kaggle
    - deepspeed
    - tqdm
    - ray
    - joblib
    - timm
    - click
    - mlflow
    - pyyaml
    - pytest
    - cameratransform
    - sqlalchemy
    - 'git+https://github.com/NilsHasNoGithub/nils-utils.git'
    - icecream
    - plotly
    # - autoalbument