name: mlip_challenge_2_autoalbum
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  # - matplotlib
  # - ipykernel
  # - ipywidgets
  # - numpy
  # - scikit-learn
  # - pillow
  # - scipy
  - pip
  - pip:
    - kaggle
    - tqdm
    - ray
    - joblib
    - timm
    - click
    - mlflow
    - pyyaml
    - pytorch-lightning
    - pytest
    - opencv-python
    - cameratransform
    - fairscale
    - deepspeed
    - sqlalchemy
    - 'git+https://github.com/NilsHasNoGithub/nils-utils.git'
    - icecream
    - autoalbument
    - '-f https://download.pytorch.org/whl/lts/1.8/torch_lts.html'
    - torch==1.9+cu111
    # - torchvision==0.9.2+cu111
    # - torchaudio==0.8.2
    # - torchtext==0.8.1
    # - albumentations