base:
  # model_type: tf_efficientnetv2_s_in21k
  model_type: tf_efficientnetv2_m_in21k
  num_epochs: 50
  optimizer: AdamW
  learning_rate: 1.0e-03
  weight_decay: 1.0e-08
  batch_size: 16
  # augmentation_preset: default
  augmentation_preset: no_aug
  gradient_accumulation: 16
  extra_model_params:
    drop_rate: 0.25
deltas:
  - augmentation_preset: default
