base:
  model_type: swin_small_patch4_window7_224
  optimizer: "AdamW"
  num_epochs: 50
  learning_rate: 1.0e-05
  weight_decay: 1.0e-08
  batch_size: 16
  gradient_accumulation: 16
  augmentation_preset: no_aug
deltas:
  - augmentation_preset: flip_rot