base:
  model_type: swin_small_patch4_window7_224
  optimizer: "AdamW"
  lr: 1.0e-05
  weight_decay: 1.0e-08
  batch_size: 16
  gradient_accumulation: 16
  augmentatopm_preset: default
deltas:
  - augmentation_preset: random_crop0